Downgrade release-docs action Py version to 3.11
Temporary downgrade the Python version to 3.11 in
the release-docs workflow to avoid a Pydantic
error when importing spacy.

TypeError: ForwardRef._evaluate() missing 1
required keyword-only argument: 'recursive_guard'